import { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import FixedHeader from "./components/FixedHeader";
import AsideMenu from "./components/AsideMenu";

const ubuntu = Ubuntu({ weight: "300", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shevalek.Space",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ubuntu.className}>
      <body className="relative">
        <FixedHeader />
        <AsideMenu />
        {children}
      </body>
    </html>
  );
}
